[window]
padding = { x = 10, y = 10}
decorations = "None"
opacity = 0.8
startup_mode = "Maximized"

[scrolling]
multiplier = 10

[font]
size = 13.0
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
bold = { family = "RobotoMono Nerd Font", style = "Bold" }
offset = { x = 0, y = 0 }
glyph_offset = { x = 0, y = 0 }
