"$schema" = 'https://starship.rs/config-schema.json'

format = """
[](c1)\
$username\
[ ](fg:c1)\
[](c3)\
$directory\
[ ](fg:c3)
($git_branch$git_commit$git_metrics$git_status$docker_context\n)\
󰘧 
"""

palette = 'pywal'

add_newline = false

[shell]
bash_indicator = ""
style = 'bold fg:c1'
disabled = false

[username]
format = '[ $user]($style)'
style_user = 'fg:c7 bg:c1'
disabled = false
show_always = true

[hostname]
format = '[󰍹 $hostname]($style)'
style = 'fg:c7 bg:c1'
ssh_only = false

[localip]
ssh_only = false
disabled = false

[netns]
disabled = false

[directory]
format = '[ $path]($style)[$read_only]($read_only_style)'
style = 'fg:c0 bg:c3'
truncation_length = 3
truncation_symbol = '...'
truncate_to_repo = false
home_symbol = "  "

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
format = '[$symbol](fg:#F1502F)[$branch(:$remote_branch)](bold) '
symbol = "󰊢 "

[git_commit]
format = '[](fg:#F1502F)[\($hash$tag\)]($style) '
style = 'bold fg:c7'
only_detached = false

[git_metrics]
disabled = false
added_style = 'bold #49ed28'
deleted_style = 'bold #ff2919'

[git_status]
format = '([status: ](bold)[\[$all_status$ahead_behind\]]($style) )'
style = 'bold fg:#F1502F'

[docker_context]
format = '[](fg:#0848ed)via [$symbol$context]($style)[](fg:#0848ed)'
style = 'bold fg:white bg:#0848ed'
symbol = " "

[nodejs]
style = 'fg:c7 bg:c4'
format = '[$symbol($version )]($style)'

[palettes.pywal]
c0 = '#1b1811'
c1 = '#86785F'
c2 = '#A9912C'
c3 = '#D1B12B'
c4 = '#E1BB26'
c5 = '#E5C327'
c6 = '#F8CF28'
c7 = '#cfc5ab'
c8 = '#908977'
c9 = '#86785F'
c10 = '#A9912C'
c11 = '#D1B12B'
c12 = '#E1BB26'
c13 = '#E5C327'
c14 = '#F8CF28'
c15 = '#cfc5ab'
